package JLex;

public enum ClaseLexica {
	NUM, BOOL, NUMERO, PCOMA, END, TRUE, FALSE, 
	IGUAL, MAS, MENOS, POR, DIV, AND, OR, NOT,
	MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, EQUIV, NOEQUIV,
	NEG, PAB, PCE, EOF, IDEN
}