
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 23 11:27:24 CEST 2018
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MENOS = 12;
  public static final int AND = 15;
  public static final int MENOR = 19;
  public static final int NEG = 24;
  public static final int MENORIGUAL = 21;
  public static final int OR = 16;
  public static final int IGUAL = 10;
  public static final int NOEQUIV = 23;
  public static final int NOT = 17;
  public static final int END = 7;
  public static final int IDEN = 4;
  public static final int TRUE = 8;
  public static final int POR = 13;
  public static final int NUM = 2;
  public static final int MAYOR = 18;
  public static final int EOF = 0;
  public static final int PCE = 26;
  public static final int DIV = 14;
  public static final int EQUIV = 22;
  public static final int MAYORIGUAL = 20;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int NUMERO = 5;
  public static final int BOOL = 3;
  public static final int PCOMA = 6;
  public static final int MAS = 11;
  public static final int PAB = 25;
}

