/* Generated By:JavaCC: Do not edit this line. ConstructorASTTinyConstants.java */
package constructorast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digito = 2;
  /** RegularExpression Id. */
  int parteDecimal = 3;
  /** RegularExpression Id. */
  int parteExponencial = 4;
  /** RegularExpression Id. */
  int num = 7;
  /** RegularExpression Id. */
  int bool = 8;
  /** RegularExpression Id. */
  int ttrue = 9;
  /** RegularExpression Id. */
  int ffalse = 10;
  /** RegularExpression Id. */
  int and = 11;
  /** RegularExpression Id. */
  int or = 12;
  /** RegularExpression Id. */
  int not = 13;
  /** RegularExpression Id. */
  int identificador = 14;
  /** RegularExpression Id. */
  int numero = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"num\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "<identificador>",
    "<numero>",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
  };

}
