
public enum ClaseLexica {
	NUM, BOOL, IDEN, PCOMA, END, TRUE, FALSE, NUMERO, 
	IGUAL, MAS, MENOS, POR, DIV, AND, OR, NOT,
	MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, EQUIV, NOEQUIV,
	NEG, PARAB, PARCE
}
